FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies including dev dependencies
RUN npm install

COPY . .

# Development mode
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"] 